version: '2'
name: ezybuy
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: ezybuy-client
    ports:
      - 5173:5173
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: ezybuy-server
    ports:
      - 3000:3000
    env_file:
      - ./server/.env